name: helmet_customer
description: ""

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependency_overrides:
  geolocator: ^13.0.3
  google_api_headers: ^4.4.0
  package_info_plus: ^8.2.1
  modal_bottom_sheet: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:  
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  
  app_settings: ^6.1.1

  get: ^4.6.6
  get_storage: ^2.1.1
  firebase_core: ^3.15.1
  # cloud_firestore: ^5.6.11
  firebase_database: ^11.3.9
  firebase_auth: ^5.6.2
  firebase_messaging: ^15.2.9
  firebase_storage: ^12.4.9
  hexcolor: ^3.0.1
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  # flutter_fortune_wheel: ^1.3.1
  modal_progress_indicator: ^1.0.3
  percent_indicator: ^4.2.3
  intl: ^0.20.2
  flutter_background_service: ^5.0.10
  shimmer: ^3.0.0
  flutter_image_slideshow: ^0.1.6
  geocoding: ^3.0.0
  geolocator: ^13.0.3
  google_maps_flutter: ^2.11.0
  location: ^8.0.0
  date_picker_plus: ^4.1.0
  maps_toolkit: ^3.1.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  moyasar: ^2.0.19
  google_maps_place_picker_mb: ^3.1.2
  date_picker_timeline: ^1.2.7
  carousel_slider: ^5.1.1
  flutter_svg: ^2.2.0
  googleapis_auth: ^2.0.0
  http: ^1.4.0
  connectivity_plus: ^6.1.4
  webview_flutter: ^4.13.0
  font_awesome_flutter: ^10.8.0
  video_player: ^2.10.0
  cloud_firestore: ^5.6.12
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/json/
    - assets/svg/
    - assets/video/
    - assets/images/profile/


  fonts:
    - family: Cairo
      fonts:
        - asset: fonts\static\Cairo-Medium.ttf
    - family: IBMPlexSansArabic
      fonts:
        - asset: fonts/static/IBMPlexSansArabic-Thin.ttf
          weight: 100
        - asset: fonts/static/IBMPlexSansArabic-ExtraLight.ttf
          weight: 200
        - asset: fonts/static/IBMPlexSansArabic-Light.ttf
          weight: 300
        - asset: fonts/static/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: fonts/static/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: fonts/static/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: fonts/static/IBMPlexSansArabic-Bold.ttf
          weight: 700
        

