// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw4H1jtPxNyfYA-tFTkiWapSqV7sD6iIs',
    appId: '1:848649324101:web:db1d20329b295e1e72052c',
    messagingSenderId: '848649324101',
    projectId: 'helmet-dac17',
    authDomain: 'helmet-dac17.firebaseapp.com',
    storageBucket: 'helmet-dac17.firebasestorage.app',
    measurementId: 'G-CM6WM38G2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB10bUvev3cL3COPb2EQwiEOVb7jRTszgo',
    appId: '1:848649324101:android:bd3c9e645f66427c72052c',
    messagingSenderId: '848649324101',
    projectId: 'helmet-dac17',
    storageBucket: 'helmet-dac17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKk7hBalNvMGarE-74wYj3bG8m7_W0pfI',
    appId: '1:848649324101:ios:c6a4949960623ab072052c',
    messagingSenderId: '848649324101',
    projectId: 'helmet-dac17',
    storageBucket: 'helmet-dac17.firebasestorage.app',
    iosBundleId: 'com.helmet.customer.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKk7hBalNvMGarE-74wYj3bG8m7_W0pfI',
    appId: '1:848649324101:ios:9d1748da4f9a22f872052c',
    messagingSenderId: '848649324101',
    projectId: 'helmet-dac17',
    storageBucket: 'helmet-dac17.firebasestorage.app',
    iosBundleId: 'com.maz.ldjobs.helmet_customer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw4H1jtPxNyfYA-tFTkiWapSqV7sD6iIs',
    appId: '1:848649324101:web:fab6d7d2bc78a42d72052c',
    messagingSenderId: '848649324101',
    projectId: 'helmet-dac17',
    authDomain: 'helmet-dac17.firebaseapp.com',
    storageBucket: 'helmet-dac17.firebasestorage.app',
    measurementId: 'G-SJJPT9HXM9',
  );
}